version: '3.8'

services:
  frontend_v1:
    build:
      context: ./frontend-service
    container_name: frontend_v1
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - TYPE=frontend_v1

  frontend_v2:
    build:
      context: ./frontend-service
    container_name: frontend_v2
    ports:
      - "3100:3000"
    environment:
      - PORT=3100
      - TYPE=frontend_v2

  frontend_v3:
    build:
      context: ./frontend-service
    container_name: frontend_v3
    ports:
      - "3200:3000"
    environment:
      - PORT=3200
      - TYPE=frontend_v3

  account-service:
    build:
      context: ./account-service
    container_name: account-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - TYPE=Account

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - TYPE=Product

  order-service-1:
    build:
      context: ./order-service
    container_name: order-service-1
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - TYPE=Order 1

  order-service-2:
    build:
      context: ./order-service
    container_name: order-service-2
    ports:
      - "3103:3003"
    environment:
      - PORT=3103
      - TYPE=Order 2

  order-service-3:
    build:
      context: ./order-service
    container_name: order-service-3
    ports:
      - "3203:3003"
    environment:
      - PORT=3203
      - TYPE=Order 3

  envoy:
    container_name: Envoy
    image: envoyproxy/envoy:v1.26.0
    user: "0:0"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./order-service-health-check.log:/var/log/envoy/order-service-health-check.log
      - ./Certificates:/etc/envoy/certs # Mount the Certificates directory for mTLS
    ports:
      - "8080:8080"  # Expose Envoy's listener
      - "9901:9901"  # Admin interface (optional for debugging)
    depends_on:
      - frontend_v1
      - frontend_v2
      - frontend_v3
      - account-service
      - product-service
      - order-service-1
      - order-service-2
      - order-service-3

name: envoy_demo